#!/bin/bash

curl -i --http2 \
--header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8" \
--compressed \
--header "Accept-Language: en-US,en;q=0.5" \
--header "Sec-Fetch-Dest: document" \
--header "Sec-Fetch-Mode: navigate" \
--header "Sec-Fetch-Site: none" \
--header "Sec-Fetch-User: ?1" \
--header "Te: trailers" \
--header "Upgrade-Insecure-Requests: 1" \
--user-agent "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0" \
"$1" | \
grep -e "laravel_session" -e "csrf" -e "fem" > temp1



cat temp1 | grep "laravel" | awk -F '[=;]' '{print $2}' | tr -d " \t\n\r" | jq -sRr @uri > cookie

cat temp1 | grep "csrf" | awk -F '["]' '{print $4}' | tr -d " \t\n\r"  | jq -sRr @uri > token

cat temp1 | grep "fem\"" | awk -F '["]' '{print $6}' | tr -d " \t\n\r" | jq -sRr @uri > id_f

cat temp1 | grep "q_fem" | awk -F '["]' '{print $6}' | tr -d " \t\n\r" | jq -sRr @uri > id_q


if [ -s id_f ]; then
        cp id_f id
else
        cp id_q id
fi
echo cookie
cat cookie
echo token
cat token
echo id
cat id
id = $(cat id)
token = $(cat token)
cookie = $(cat cookie)


curl \
--header "Content-Type: application/x-www-form-urlencoded; charset=UTF-8" \
--compressed \
--header "Accept-Language: en-US,en;q=0.5" \
--cookie "laravel_session=$cookie;ppu_main_3d9364e08b38a312f0fb17c14107437e=1; ppu_sub_3d9364e08b38a312f0fb17c14107437e=1" \
--header "Origin: https://streamm4u.com" \
--header "Referer: https://streamm4u.com/watch/movie/automata-2014.1265.html" \
--header "Sec-Fetch-Dest: empty" \
--header "Sec-Fetch-Mode: cors" \
--header "Sec-Fetch-Site: same-origin" \
--header "Te: trailers" \
--user-agent "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0" \
--header "X-Requested-With: XMLHttpRequest" \
--data-binary "_token=$token&m4u=$id" \
https://streamm4u.com/anhjax \
-o output.json

# now It should bypass cloudflare and recieve a json file with the embeded link, and we can proceed from there, but, something's wrong, and I don't know what
# probably with the variables, but i'm not exactly great with bash..,
# For any help, Thanks in advance.
